#  These annotations are used to configure the Vault Agent to inject secrets into the pod volume.
#
#  vault.hashicorp.com/agent-inject: “true”: Enables Vault Agent injection for this pod.
#  vault.hashicorp.com/agent-inject-status: “update”: Ensures the status of secret injection is updated.
#  vault.hashicorp.com/agent-inject-secret-login: “secret/cloudbees-login”: Specifies that the secret stored at secret/cloudbees-login in Vault should be injected.
#  vault.hashicorp.com/agent-inject-template-cloudbees-login: Defines the template for the injected login secret, specifying the format in which the secret will be written.
#  vault.hashicorp.com/role: “vault-role”: Specifies the Vault role to be used for authentication.
#  serviceAccountName: Uses the service account vault-serviceaccount which has permissions to access Vault.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test
  labels:
    app: read-vault-secret
spec:
  selector:
    matchLabels:
      app: read-vault-secret
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-cloudbees-login: "secret/cloudbees-login"
        vault.hashicorp.com/agent-inject-template-cloudbees-login: |
          {{- with secret "secret/cloudbees-login" -}}
          username={{ .Data.data.username }}
          password={{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/role: "vault-role"
      labels:
        app: read-vault-secret
    spec:
      serviceAccountName: vault-serviceaccount
      containers:
        - name: nginx
          image: nginx